id: I79AB11FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:41:00+00:00'
last_modified: '2022-06-07T18:04:33.456746+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20408
  title: རྣམ་འགྲེལ་བསྡུས་དོན་མི་ཕམ་ཞལ་ལུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EEE:
      image_group_id: I5057
      title: ''
      total_pages: 328
      order: 1
      base_file: 1EEE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
