id: P003172
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20408
  title: རྣམ་འགྲེལ་བསྡུས་དོན་མི་ཕམ་ཞལ་ལུང
  author: ''
  volumes:
    ab61e4edf28a494b8e01b9a104bcb341:
      image_group_id: I5057
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
